name: Elevators
version: 1.0.0
main: jp.havenmc.elevators.Elevators
api-version: '1.21'
author: ryusei_sky

commands:
  elevators-reload:
    permission: elevator.reload

permissions:
  elevator.use:
    default: true
  elevator.reload:
    default: op
